all:
	i686-elf-as boot.s -o boot.o
	i686-elf-gcc -c kernel.c -o kernel.o -std=gnu99 -ffreestanding -O0 -Wall -Wextra
	i686-elf-gcc -T linker.ld -o kernel.bin -ffreestanding -O0 -nostdlib boot.o kernel.o -lgcc

clean:
	rm -f *.o
	rm -f *.bin

